### ISSUE TITLE
move codecov to base coverage report

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#167] opened 2024-03-04 18:25 UTC
Sometimes Codecov gives us a hard time and causes errors. I believe we should consider transitioning to using the base pytest coverage report instead. This can be achieved with the GitHub app called Smokeshow: https://github.com/samuelcolvin/smokeshow
I've already implemented this approach in a few repositories, and it has been working great. For example, you can check out the configuration in our bbconf repository:
e.g. https://github.com/databio/bbconf/blob/master/.github/workflows/cli-coverage.yml

**Comment by nsheff** [comment] 2024-03-12 14:26
It's fine with me.

**Comment by donaldcampbelljr** [comment] 2024-04-03 16:03
I was able to add your workflow as suggested. Interestingly, I get different results if I run the process locally vs via github actions:
![image](https://github.com/pepkit/pipestat/assets/125581724/8c12e0fe-42df-43a9-87ca-120bdd614963)

Digging into this, it looks like our db tests are skipping (for both pytest and this code coverage workflow). I did add the proper dependencies and confirmed the db parameters were correct.
![image](https://github.com/pepkit/pipestat/assets/125581724/49b104b1-b0dc-449e-b1a1-773f1ea916c3)

The check exists within `conftest.py`:
```
try:
    subprocess.check_output(
        "docker inspect pipestat_test_db --format '{{.State.Status}}'", shell=True
    )
    SERVICE_UNAVAILABLE = False
except:
    register(print, f"Some tests require a test database. To initiate it, run:\n{DB_CMD}")
    SERVICE_UNAVAILABLE = True
```

**Comment by khoroshevskyi** [comment] 2024-04-11 15:31
Did you set up database correctly?

**Comment by donaldcampbelljr** [comment] 2024-04-12 17:06
Nathan and I discussed this issue. We are going to remove coverage via GHA and instead just occasionally run it locally to ensure we are not going too low (threshold ~ 50-60% coverage).

**Comment by donaldcampbelljr** [comment] 2024-04-12 17:07
Closing for now as `won't fix`

**Closed by donaldcampbelljr** 2024-04-12 17:07 UTC
